# Generated by Django 5.2.4 on 2025-07-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc')], max_length=100)),
                ('niveau', models.CharField(choices=[('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('2nde', '2nde'), ('1ère', '1ère'), ('Tle', 'Terminale')], max_length=20)),
                ('exam_file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('correction_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
