# Generated by Django 5.1.6 on 2025-07-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('rouge', 'Rouge'), ('blanc', 'Blanc')], max_length=100)),
                ('diploma_type', models.CharField(choices=[('none', 'Aucun diplôme'), ('bepec', 'BEPC'), ('bac', 'Baccalauréat')], default='none', max_length=100)),
                ('serie_bac', models.CharField(blank=True, choices=[('A', 'Série A'), ('C', 'Série C'), ('D', 'Série D'), ('E', 'Série E'), ('F', 'Série F'), ('F1', 'Série F1'), ('F2', 'Série F2'), ('F3', 'Série F3'), ('F4', 'Série F4'), ('H', 'Série H'), ('G', 'Série G'), ('TI', 'Série TI'), ('autre', 'Autre série')], help_text='Renseigné uniquement si diplôme = Bac', max_length=10, null=True)),
                ('exam_file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('correction_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
